# Generated by Django 6.0.7 on 2026-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar ($)'), ('ARS', 'Peso Argentino ($)')], default='EUR', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de perfil'),
        ),
    ]
